fixing pylint for CI/CD

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -5,19 +5,34 @@ on: [push, pull_request]
 jobs:
   lint:
     runs-on: ubuntu-latest
+
     steps:
     - uses: actions/checkout@v2
+
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.x'
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install -r requirements.txt
-    - name: Run autopep8
-      run: |
-        autopep8 --in-place --aggressive --aggressive **/*.py
+        pip install pylint
+
     - name: Run pylint
+      id: pylint
       run: |
-        pylint **/*.py
+          pylint **/*.py > pylint_report.txt || true
+
+    - name: Check pylint score
+      id: check_score
+      run: |
+        score=$(grep 'Your code has been rated at' pylint_report.txt | awk '{print $7}' | cut -d/ -f1)
+        echo "Pylint score: $score"
+        if (( $(echo "$score > 8.0" | bc -l) )); then
+          echo "Pylint check passed"
+          exit 0
+        else
+          echo "Pylint check failed"
+          exit 1
+        fi
